name: architecture-labs-realtime-websocket

networks:
  observability:
    external: true
    name: architecture-labs-observability

services:

  ui:
    build:
      context: ../../walkthrough-ui
      dockerfile: Dockerfile
    container_name: architecture-labs-realtime-websocket-ui
    ports:
      - "15173:80"
    networks:
      - observability
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server

  server:
    build:
      context: ./src/Server
    container_name: architecture-labs-realtime-websocket-server

    ports:
      - "5000:8080"

    networks:
      - observability

    environment:
      ASPNETCORE_ENVIRONMENT: Development
