global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'csharp-api'
    static_configs:
      - targets: ['api-service:8080'] # Points directly to your API's network container
  - job_name: 'windows-host-os'
    static_configs:
    # 'host.docker.internal' bridges the internal Docker network back out to your Windows host ports
    - targets: ['host.docker.internal:9182']
